export const constraints = [
  'all words must have a word embedded in them, spelling-wise, but MUST NOT be compound words. Categories MUST not be "words containing ONE" but instead like "words containing spelled numbers"',
  'all words must be 3 letters, but categories must be MUST specific than "3-letter words"',
  'all words must be 4 letters, but categories must be MUST specific than "4-letter words"',
  'all words must be 5 letters, but categories must be MUST specific than "5-letter words"',
  'all words must have double letters, but categories MUST be more specific than "words with double letters" or "words that contain \"look\""',
  'all words must be compound words, but categories MUST be more specific than "words that contain \"look\"" or "compound words" (for example: "words containing animals")',
  'most words should be part of famous phrases or the title of a famous work (tv show, movie, book, etc)',
  'most words should have a Z in them, but categories MUST be more specific than "words with a Z"',
  'most words should have a Q in them, but categories MUST be more specific than "words with a Q"',
  'all words must begin with the same letter, but categories MUST be more specific than "words beginning with L". There should be one beginning letter for the game. The beginning letter should not be different in different categories.',
  'all words must end with the same letter, but categories MUST be more specific than "words ending with Y". There should be one ending letter for the game. The ending letter should not be different in different categories.',
  'all words must end in the same suffix (-ing, -er, -ly, etc), but categories MUST be more specific than "words ending with the suffix -ing". There should be one suffix for the game. The suffix should not be different in different categories.',
  'most words should rhyme with each other. There should be one rhyming sound for the game. The rhyming sound should not be different in different categories.',
  'all words must have silent letters, but categories MUST be more specific than "words with silent letters" or "words with silent B")',
  'most should have letters in alphabetical order, but categories MUST be more specific than "words with alphabetical letters"',
  'most should have letters in reverse-alphabetical order, but categories MUST be more specific than "words with reverse-alphabetical letters"',
  'all words must have 1 syllable, but categories MUST be more specific than "one-syllable words"',
  'all words must have 2 syllables, but categories MUST be more specific than "two-syllable words"',
  'all words must have 3 syllables, but categories MUST be more specific than "three-syllable words"',
  'all words must have 4 syllables, but categories MUST be more specific than "four-syllable words"',
  'all words must be REAL WORDS formed by removing one letter from longer words, but the letter removed CANNOT be S at the end of a word',
  'always generate 5 categories rather than 4',
]
