export const constraints = [
  'all words must be a number, but categories MUST NOT be "numbers under 5" or "words that are numbers" or similar',
  'all words must be a country, but categories MUST be more specific than "countries" (for example: "mediterranean countries")',
  'all words must be a city, but categories MUST be more specific than "cities" (for example: "US state capitals")',
  'all words must be a state, provice, or territory, but categories MUST be more specific than "state" (for example: "Midwest states")',
  'all words must have a word embedded in them, spelling-wise, but MUST NOT be compound words. Categories MUST not be "words containing ONE" but instead "words containing spelled numbers"',
  'all words must be an animal, but categories MUST be more specific than "animals" (for example: "carnivores")',
  'all words must be food, but categories MUST be more specific than "food" (for example: "vegetables related to broccoli")',
  'all words must be names or nicknames, but categories MUST be more specific than "nicknames" (for example: "presidental nicknames")',
  'all words must be 3 letters, but categories must be MUST specific than "3-letter words"',
  'all words must be 2 letters, but categories must be MUST specific than "2-letter words"',
  'all words must have double letters, but categories MUST be more specific than "words with double letters" or "words that contain \"look\""',
  'all words must be compound words, but categories MUST be more specific than "words that contain \"look\"" or "compound words" (for example: "words containing animals")',
  'most words should be part of famous phrases or the title of a famous work (tv show, movie, book, etc)',
  'most words should have a Z in them, but categories MUST be more specific than "words with a Z"',
  'most words should have a Q in them, but categories MUST be more specific than "words with a Q"',
  'all words must begin with the same letter, but categories MUST be more specific than "words beginning with L"',
  'all words must end in the same suffix (-ing, -er, -ly, etc), but categories MUST be more specific than "words ending with the suffix -ing"',
  'most words should rhyme with each other',
]
